# This file is for GitHub Sponsors information
# GitHub will display a "Sponsor this project" button in the repository
# You can customize this file with your sponsorship options

github: MaxAndreev27
patreon:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
# polar:
