# Generated by Django 5.1.3 on 2026-08-29 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_contact"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="account.Contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
